# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getDownAndInPutOption <- function(nInt, Strike, Spot, Vol, Rfr, Expiry, Barrier, nReps = 1000L) {
    .Call(`_appfinRcpp_getDownAndInPutOption`, nInt, Strike, Spot, Vol, Rfr, Expiry, Barrier, nReps)
}

rcpp_hello <- function() {
    .Call(`_appfinRcpp_rcpp_hello`)
}

